package ovh.maddie480.randomstuff.backend.discord.timezonebot;

import org.jsoup.Jsoup;
import org.jsoup.nodes.Element;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.File;
import java.io.IOException;
import java.time.DateTimeException;
import java.time.ZoneId;
import java.util.*;

public class TimezoneNamesDB {
    private static final Logger logger = LoggerFactory.getLogger(TimezoneNamesDB.class);

    static final Map<String, String> TIMEZONE_MAP;
    static final Map<String, String> TIMEZONE_FULL_NAMES;
    static final Map<String, List<String>> TIMEZONE_CONFLICTS;

    // offset timezone database
    static {
        TIMEZONE_MAP = new HashMap<>();
        TIMEZONE_MAP.put("Argentina Time", "UTC-3");
        TIMEZONE_MAP.put("SCT", "UTC+4");
        TIMEZONE_MAP.put("Acre Time", "UTC-5");
        TIMEZONE_MAP.put("CHAST", "UTC+12:45");
        TIMEZONE_MAP.put("Pierre & Miquelon Daylight Time", "UTC-2");
        TIMEZONE_MAP.put("FJT", "UTC+12");
        TIMEZONE_MAP.put("SAKT", "UTC+11");
        TIMEZONE_MAP.put("Atlantic Daylight Time", "UTC-3");
        TIMEZONE_MAP.put("Papua New Guinea Time", "UTC+10");
        TIMEZONE_MAP.put("AKST", "UTC-9");
        TIMEZONE_MAP.put("Australian Eastern Daylight Time", "UTC+11");
        TIMEZONE_MAP.put("NOVT", "UTC+7");
        TIMEZONE_MAP.put("Solomon Islands Time", "UTC+11");
        TIMEZONE_MAP.put("Vanuatu Time", "UTC+11");
        TIMEZONE_MAP.put("TAHT", "UTC-10");
        TIMEZONE_MAP.put("GAMT", "UTC-9");
        TIMEZONE_MAP.put("LINT", "UTC+14");
        TIMEZONE_MAP.put("PONT", "UTC+11");
        TIMEZONE_MAP.put("UYST", "UTC-2");
        TIMEZONE_MAP.put("Novosibirsk Summer Time", "UTC+7");
        TIMEZONE_MAP.put("TFT", "UTC+5");
        TIMEZONE_MAP.put("New Caledonia Time", "UTC+11");
        TIMEZONE_MAP.put("Pitcairn Standard Time", "UTC-8");
        TIMEZONE_MAP.put("MYT", "UTC+8");
        TIMEZONE_MAP.put("JST", "UTC+9");
        TIMEZONE_MAP.put("ACDT", "UTC+10:30");
        TIMEZONE_MAP.put("FKT", "UTC-4");
        TIMEZONE_MAP.put("GMT", "UTC+0");
        TIMEZONE_MAP.put("Iran Standard Time", "UTC+03:30");
        TIMEZONE_MAP.put("CET", "UTC+1");
        TIMEZONE_MAP.put("EASST", "UTC-5");
        TIMEZONE_MAP.put("French Southern and Antarctic Time", "UTC+5");
        TIMEZONE_MAP.put("French Guiana Time", "UTC-3");
        TIMEZONE_MAP.put("Amazon Summer Time", "UTC-3");
        TIMEZONE_MAP.put("A", "UTC+1");
        TIMEZONE_MAP.put("B", "UTC+2");
        TIMEZONE_MAP.put("C", "UTC+3");
        TIMEZONE_MAP.put("AZST", "UTC+5");
        TIMEZONE_MAP.put("D", "UTC+4");
        TIMEZONE_MAP.put("E", "UTC+5");
        TIMEZONE_MAP.put("F", "UTC+6");
        TIMEZONE_MAP.put("G", "UTC+7");
        TIMEZONE_MAP.put("H", "UTC+8");
        TIMEZONE_MAP.put("I", "UTC+9");
        TIMEZONE_MAP.put("K", "UTC+10");
        TIMEZONE_MAP.put("Yap Time", "UTC+10");
        TIMEZONE_MAP.put("L", "UTC+11");
        TIMEZONE_MAP.put("M", "UTC+12");
        TIMEZONE_MAP.put("N", "UTC-1");
        TIMEZONE_MAP.put("O", "UTC-2");
        TIMEZONE_MAP.put("P", "UTC-3");
        TIMEZONE_MAP.put("Q", "UTC-4");
        TIMEZONE_MAP.put("R", "UTC-5");
        TIMEZONE_MAP.put("S", "UTC-6");
        TIMEZONE_MAP.put("SAMT", "UTC+4");
        TIMEZONE_MAP.put("T", "UTC-7");
        TIMEZONE_MAP.put("U", "UTC-8");
        TIMEZONE_MAP.put("V", "UTC-9");
        TIMEZONE_MAP.put("W", "UTC-10");
        TIMEZONE_MAP.put("X", "UTC-11");
        TIMEZONE_MAP.put("Y", "UTC-12");
        TIMEZONE_MAP.put("Z", "UTC+0");
        TIMEZONE_MAP.put("Cuba Daylight Time", "UTC-4");
        TIMEZONE_MAP.put("Azerbaijan Time", "UTC+4");
        TIMEZONE_MAP.put("YEKST", "UTC+6");
        TIMEZONE_MAP.put("Kuybyshev Time", "UTC+4");
        TIMEZONE_MAP.put("NFDT", "UTC+12");
        TIMEZONE_MAP.put("IRKT", "UTC+8");
        TIMEZONE_MAP.put("Yekaterinburg Summer Time", "UTC+6");
        TIMEZONE_MAP.put("ACT", "UTC-5");
        TIMEZONE_MAP.put("Moscow Daylight Time", "UTC+4");
        TIMEZONE_MAP.put("Alaska Standard Time", "UTC-9");
        TIMEZONE_MAP.put("Pyongyang Time", "UTC+08:30");
        TIMEZONE_MAP.put("Kamchatka Summer Time", "UTC+12");
        TIMEZONE_MAP.put("Kosrae Time", "UTC+11");
        TIMEZONE_MAP.put("RET", "UTC+4");
        TIMEZONE_MAP.put("SGT", "UTC+8");
        TIMEZONE_MAP.put("X-ray Time Zone", "UTC-11");
        TIMEZONE_MAP.put("Turkmenistan Time", "UTC+5");
        TIMEZONE_MAP.put("Vladivostok Time", "UTC+10");
        TIMEZONE_MAP.put("India Time Zone", "UTC+9");
        TIMEZONE_MAP.put("FNT", "UTC-2");
        TIMEZONE_MAP.put("Hotel Time Zone", "UTC+8");
        TIMEZONE_MAP.put("East Greenland Time", "UTC-1");
        TIMEZONE_MAP.put("Krasnoyarsk Summer Time", "UTC+8");
        TIMEZONE_MAP.put("Pacific Daylight Time", "UTC-7");
        TIMEZONE_MAP.put("CLST", "UTC-3");
        TIMEZONE_MAP.put("Fiji Time", "UTC+12");
        TIMEZONE_MAP.put("Alfa Time Zone", "UTC+1");
        TIMEZONE_MAP.put("WITA", "UTC+8");
        TIMEZONE_MAP.put("Charlie Time Zone", "UTC+3");
        TIMEZONE_MAP.put("OMST", "UTC+6");
        TIMEZONE_MAP.put("TJT", "UTC+5");
        TIMEZONE_MAP.put("Central Indonesian Time", "UTC+8");
        TIMEZONE_MAP.put("HST", "UTC-10");
        TIMEZONE_MAP.put("Anadyr Time", "UTC+12");
        TIMEZONE_MAP.put("ANAST", "UTC+12");
        TIMEZONE_MAP.put("CIDST", "UTC-4");
        TIMEZONE_MAP.put("Western Greenland Summer Time", "UTC-1");
        TIMEZONE_MAP.put("Pohnpei Standard Time", "UTC+11");
        TIMEZONE_MAP.put("Uruguay Time", "UTC-3");
        TIMEZONE_MAP.put("Singapore Time", "UTC+8");
        TIMEZONE_MAP.put("ULAST", "UTC+9");
        TIMEZONE_MAP.put("TKT", "UTC+13");
        TIMEZONE_MAP.put("Brunei Darussalam Time", "UTC+8");
        TIMEZONE_MAP.put("Chamorro Standard Time", "UTC+10");
        TIMEZONE_MAP.put("Western Argentine Summer Time", "UTC-3");
        TIMEZONE_MAP.put("Yekaterinburg Time", "UTC+5");
        TIMEZONE_MAP.put("AFT", "UTC+04:30");
        TIMEZONE_MAP.put("Western European Time", "UTC+0");
        TIMEZONE_MAP.put("Hovd Summer Time", "UTC+8");
        TIMEZONE_MAP.put("Reunion Time", "UTC+4");
        TIMEZONE_MAP.put("TLT", "UTC+9");
        TIMEZONE_MAP.put("PDT", "UTC-7");
        TIMEZONE_MAP.put("Vladivostok Summer Time", "UTC+11");
        TIMEZONE_MAP.put("Coordinated Universal Time", "UTC+0");
        TIMEZONE_MAP.put("Novosibirsk Time", "UTC+7");
        TIMEZONE_MAP.put("CKT", "UTC-10");
        TIMEZONE_MAP.put("Malaysia Time", "UTC+8");
        TIMEZONE_MAP.put("TMT", "UTC+5");
        TIMEZONE_MAP.put("Ecuador Time", "UTC-5");
        TIMEZONE_MAP.put("LHST", "UTC+10:30");
        TIMEZONE_MAP.put("PET", "UTC-5");
        TIMEZONE_MAP.put("AWST", "UTC+8");
        TIMEZONE_MAP.put("NZST", "UTC+12");
        TIMEZONE_MAP.put("SAST", "UTC+2");
        TIMEZONE_MAP.put("CLT", "UTC-4");
        TIMEZONE_MAP.put("Chuuk Time", "UTC+10");
        TIMEZONE_MAP.put("Central Daylight Time", "UTC-5");
        TIMEZONE_MAP.put("Wallis and Futuna Time", "UTC+12");
        TIMEZONE_MAP.put("CHOT", "UTC+8");
        TIMEZONE_MAP.put("Cook Island Time", "UTC-10");
        TIMEZONE_MAP.put("Echo Time Zone", "UTC+5");
        TIMEZONE_MAP.put("Tonga Summer Time", "UTC+14");
        TIMEZONE_MAP.put("WGST", "UTC-1");
        TIMEZONE_MAP.put("East Timor Time", "UTC+9");
        TIMEZONE_MAP.put("Gulf Standard Time", "UTC+4");
        TIMEZONE_MAP.put("Omsk Standard Time", "UTC+6");
        TIMEZONE_MAP.put("West Samoa Time", "UTC+13");
        TIMEZONE_MAP.put("Eastern Standard Time", "UTC-5");
        TIMEZONE_MAP.put("Lord Howe Daylight Time", "UTC+11");
        TIMEZONE_MAP.put("ULAT", "UTC+8");
        TIMEZONE_MAP.put("Arabia Standard Time", "UTC+3");
        TIMEZONE_MAP.put("Australian Western Daylight Time", "UTC+9");
        TIMEZONE_MAP.put("Nauru Time", "UTC+12");
        TIMEZONE_MAP.put("TOT", "UTC+13");
        TIMEZONE_MAP.put("Oscar Time Zone", "UTC-2");
        TIMEZONE_MAP.put("PMST", "UTC-3");
        TIMEZONE_MAP.put("PGT", "UTC+10");
        TIMEZONE_MAP.put("ANAT", "UTC+12");
        TIMEZONE_MAP.put("NCT", "UTC+11");
        TIMEZONE_MAP.put("VLAT", "UTC+10");
        TIMEZONE_MAP.put("China Standard Time", "UTC+8");
        TIMEZONE_MAP.put("Falkland Island Time", "UTC-4");
        TIMEZONE_MAP.put("Newfoundland Daylight Time", "UTC-02:30");
        TIMEZONE_MAP.put("Mountain Daylight Time", "UTC-6");
        TIMEZONE_MAP.put("Central European Time", "UTC+1");
        TIMEZONE_MAP.put("Fiji Summer Time", "UTC+13");
        TIMEZONE_MAP.put("Yakutsk Summer Time", "UTC+10");
        TIMEZONE_MAP.put("CIST", "UTC-5");
        TIMEZONE_MAP.put("Irkutsk Time", "UTC+8");
        TIMEZONE_MAP.put("Davis Time", "UTC+7");
        TIMEZONE_MAP.put("YEKT", "UTC+5");
        TIMEZONE_MAP.put("Chatham Island Daylight Time", "UTC+13:45");
        TIMEZONE_MAP.put("PHT", "UTC+8");
        TIMEZONE_MAP.put("Central European Summer Time", "UTC+2");
        TIMEZONE_MAP.put("NDT", "UTC-02:30");
        TIMEZONE_MAP.put("EST", "UTC-5");
        TIMEZONE_MAP.put("Israel Daylight Time", "UTC+3");
        TIMEZONE_MAP.put("IRST", "UTC+03:30");
        TIMEZONE_MAP.put("COT", "UTC-5");
        TIMEZONE_MAP.put("November Time Zone", "UTC-1");
        TIMEZONE_MAP.put("Amazon Time", "UTC-4");
        TIMEZONE_MAP.put("ORAT", "UTC+5");
        TIMEZONE_MAP.put("VUT", "UTC+11");
        TIMEZONE_MAP.put("Christmas Island Time", "UTC+7");
        TIMEZONE_MAP.put("Tonga Time", "UTC+13");
        TIMEZONE_MAP.put("Yankee Time Zone", "UTC-12");
        TIMEZONE_MAP.put("UTC", "UTC+0");
        TIMEZONE_MAP.put("ChST", "UTC+10");
        TIMEZONE_MAP.put("WEST", "UTC+1");
        TIMEZONE_MAP.put("BNT", "UTC+8");
        TIMEZONE_MAP.put("Armenia Summer Time", "UTC+5");
        TIMEZONE_MAP.put("Marquesas Time", "UTC-09:30");
        TIMEZONE_MAP.put("Turkey Time", "UTC+3");
        TIMEZONE_MAP.put("TRT", "UTC+3");
        TIMEZONE_MAP.put("AEST", "UTC+10");
        TIMEZONE_MAP.put("New Zealand Daylight Time", "UTC+13");
        TIMEZONE_MAP.put("WAKT", "UTC+12");
        TIMEZONE_MAP.put("Lima Time Zone", "UTC+11");
        TIMEZONE_MAP.put("MDT", "UTC-6");
        TIMEZONE_MAP.put("NFT", "UTC+11");
        TIMEZONE_MAP.put("MAGT", "UTC+11");
        TIMEZONE_MAP.put("Azores Time", "UTC-1");
        TIMEZONE_MAP.put("GYT", "UTC-4");
        TIMEZONE_MAP.put("BOT", "UTC-4");
        TIMEZONE_MAP.put("Armenia Time", "UTC+4");
        TIMEZONE_MAP.put("Tango Time Zone", "UTC-7");
        TIMEZONE_MAP.put("Azores Summer Time", "UTC+0");
        TIMEZONE_MAP.put("Mike Time Zone", "UTC+12");
        TIMEZONE_MAP.put("Australian Central Western Standard Time", "UTC+08:45");
        TIMEZONE_MAP.put("AoE", "UTC-12");
        TIMEZONE_MAP.put("PKT", "UTC+5");
        TIMEZONE_MAP.put("Bravo Time Zone", "UTC+2");
        TIMEZONE_MAP.put("Moscow Standard Time", "UTC+3");
        TIMEZONE_MAP.put("Bolivia Time", "UTC-4");
        TIMEZONE_MAP.put("Seychelles Time", "UTC+4");
        TIMEZONE_MAP.put("FKST", "UTC-3");
        TIMEZONE_MAP.put("GILT", "UTC+12");
        TIMEZONE_MAP.put("SRT", "UTC-3");
        TIMEZONE_MAP.put("CHUT", "UTC+10");
        TIMEZONE_MAP.put("Wake Time", "UTC+12");
        TIMEZONE_MAP.put("CHADT", "UTC+13:45");
        TIMEZONE_MAP.put("Japan Standard Time", "UTC+9");
        TIMEZONE_MAP.put("Line Islands Time", "UTC+14");
        TIMEZONE_MAP.put("Suriname Time", "UTC-3");
        TIMEZONE_MAP.put("Australian Central Daylight Time", "UTC+10:30");
        TIMEZONE_MAP.put("SST", "UTC-11");
        TIMEZONE_MAP.put("Aqtobe Time", "UTC+5");
        TIMEZONE_MAP.put("PHOT", "UTC+13");
        TIMEZONE_MAP.put("Ulaanbaatar Time", "UTC+8");
        TIMEZONE_MAP.put("Alaska Daylight Time", "UTC-8");
        TIMEZONE_MAP.put("BRT", "UTC-3");
        TIMEZONE_MAP.put("FJST", "UTC+13");
        TIMEZONE_MAP.put("IRKST", "UTC+9");
        TIMEZONE_MAP.put("Yakutsk Time", "UTC+9");
        TIMEZONE_MAP.put("Iran Daylight Time", "UTC+04:30");
        TIMEZONE_MAP.put("Eastern European Summer Time", "UTC+3");
        TIMEZONE_MAP.put("Pakistan Standard Time", "UTC+5");
        TIMEZONE_MAP.put("Gambier Time", "UTC-9");
        TIMEZONE_MAP.put("PYST", "UTC-3");
        TIMEZONE_MAP.put("Romeo Time Zone", "UTC-5");
        TIMEZONE_MAP.put("Australian Eastern Standard Time", "UTC+10");
        TIMEZONE_MAP.put("Azerbaijan Summer Time", "UTC+5");
        TIMEZONE_MAP.put("TVT", "UTC+12");
        TIMEZONE_MAP.put("Delta Time Zone", "UTC+4");
        TIMEZONE_MAP.put("Cuba Standard Time", "UTC-5");
        TIMEZONE_MAP.put("MHT", "UTC+12");
        TIMEZONE_MAP.put("West Africa Time", "UTC+1");
        TIMEZONE_MAP.put("Hawaii-Aleutian Daylight Time", "UTC-9");
        TIMEZONE_MAP.put("Samara Time", "UTC+4");
        TIMEZONE_MAP.put("ACST", "UTC+09:30");
        TIMEZONE_MAP.put("Pierre & Miquelon Standard Time", "UTC-3");
        TIMEZONE_MAP.put("Anadyr Summer Time", "UTC+12");
        TIMEZONE_MAP.put("AKDT", "UTC-8");
        TIMEZONE_MAP.put("HOVT", "UTC+7");
        TIMEZONE_MAP.put("ACWST", "UTC+08:45");
        TIMEZONE_MAP.put("KUYT", "UTC+4");
        TIMEZONE_MAP.put("Norfolk Daylight Time", "UTC+12");
        TIMEZONE_MAP.put("Further-Eastern European Time", "UTC+3");
        TIMEZONE_MAP.put("UYT", "UTC-3");
        TIMEZONE_MAP.put("Venezuelan Standard Time", "UTC-4");
        TIMEZONE_MAP.put("Australian Central Standard Time", "UTC+09:30");
        TIMEZONE_MAP.put("Ulaanbaatar Summer Time", "UTC+9");
        TIMEZONE_MAP.put("Myanmar Time", "UTC+06:30");
        TIMEZONE_MAP.put("Greenwich Mean Time", "UTC+0");
        TIMEZONE_MAP.put("Indian Chagos Time", "UTC+6");
        TIMEZONE_MAP.put("TOST", "UTC+14");
        TIMEZONE_MAP.put("CVT", "UTC-1");
        TIMEZONE_MAP.put("Western European Summer Time", "UTC+1");
        TIMEZONE_MAP.put("ART", "UTC-3");
        TIMEZONE_MAP.put("BTT", "UTC+6");
        TIMEZONE_MAP.put("Irkutsk Summer Time", "UTC+9");
        TIMEZONE_MAP.put("Colombia Time", "UTC-5");
        TIMEZONE_MAP.put("UZT", "UTC+5");
        TIMEZONE_MAP.put("Brasília Time", "UTC-3");
        TIMEZONE_MAP.put("YAKT", "UTC+9");
        TIMEZONE_MAP.put("CEST", "UTC+2");
        TIMEZONE_MAP.put("Kilo Time Zone", "UTC+10");
        TIMEZONE_MAP.put("Bangladesh Standard Time", "UTC+6");
        TIMEZONE_MAP.put("South Georgia Time", "UTC-2");
        TIMEZONE_MAP.put("Central Africa Time", "UTC+2");
        TIMEZONE_MAP.put("KGT", "UTC+6");
        TIMEZONE_MAP.put("ICT", "UTC+7");
        TIMEZONE_MAP.put("CXT", "UTC+7");
        TIMEZONE_MAP.put("Fernando de Noronha Time", "UTC-2");
        TIMEZONE_MAP.put("WAST", "UTC+2");
        TIMEZONE_MAP.put("Hovd Time", "UTC+7");
        TIMEZONE_MAP.put("Oral Time", "UTC+5");
        TIMEZONE_MAP.put("Marshall Islands Time", "UTC+12");
        TIMEZONE_MAP.put("Cayman Islands Standard Time", "UTC-5");
        TIMEZONE_MAP.put("MAGST", "UTC+12");
        TIMEZONE_MAP.put("IDT", "UTC+3");
        TIMEZONE_MAP.put("Pacific Standard Time", "UTC-8");
        TIMEZONE_MAP.put("Uniform Time Zone", "UTC-8");
        TIMEZONE_MAP.put("EGST", "UTC+0");
        TIMEZONE_MAP.put("Sierra Time Zone", "UTC-6");
        TIMEZONE_MAP.put("Cayman Islands Daylight Saving Time", "UTC-4");
        TIMEZONE_MAP.put("Easter Island Standard Time", "UTC-6");
        TIMEZONE_MAP.put("Krasnoyarsk Time", "UTC+7");
        TIMEZONE_MAP.put("Western Sahara Standard Time", "UTC+0");
        TIMEZONE_MAP.put("AQTT", "UTC+5");
        TIMEZONE_MAP.put("BRST", "UTC-2");
        TIMEZONE_MAP.put("PST", "UTC-8");
        TIMEZONE_MAP.put("MMT", "UTC+06:30");
        TIMEZONE_MAP.put("Korea Standard Time", "UTC+9");
        TIMEZONE_MAP.put("Zulu Time Zone", "UTC+0");
        TIMEZONE_MAP.put("Chile Standard Time", "UTC-4");
        TIMEZONE_MAP.put("Magadan Time", "UTC+11");
        TIMEZONE_MAP.put("HOVST", "UTC+8");
        TIMEZONE_MAP.put("WAT", "UTC+1");
        TIMEZONE_MAP.put("Western Indonesian Time", "UTC+7");
        TIMEZONE_MAP.put("Palau Time", "UTC+9");
        TIMEZONE_MAP.put("NPT", "UTC+05:45");
        TIMEZONE_MAP.put("Chile Summer Time", "UTC-3");
        TIMEZONE_MAP.put("HDT", "UTC-9");
        TIMEZONE_MAP.put("Tahiti Time", "UTC-10");
        TIMEZONE_MAP.put("WT", "UTC+0");
        TIMEZONE_MAP.put("YAKST", "UTC+10");
        TIMEZONE_MAP.put("Papa Time Zone", "UTC-3");
        TIMEZONE_MAP.put("Atlantic Standard Time", "UTC-4");
        TIMEZONE_MAP.put("Galapagos Time", "UTC-6");
        TIMEZONE_MAP.put("KOST", "UTC+11");
        TIMEZONE_MAP.put("Irish Standard Time", "UTC+1");
        TIMEZONE_MAP.put("Victor Time Zone", "UTC-9");
        TIMEZONE_MAP.put("Hawaii Standard Time", "UTC-10");
        TIMEZONE_MAP.put("SYOT", "UTC+3");
        TIMEZONE_MAP.put("VOST", "UTC+6");
        TIMEZONE_MAP.put("Easter Island Summer Time", "UTC-5");
        TIMEZONE_MAP.put("MART", "UTC-09:30");
        TIMEZONE_MAP.put("Mawson Time", "UTC+5");
        TIMEZONE_MAP.put("Western Sahara Summer Time", "UTC+1");
        TIMEZONE_MAP.put("Syowa Time", "UTC+3");
        TIMEZONE_MAP.put("Eastern European Time", "UTC+2");
        TIMEZONE_MAP.put("Anywhere on Earth", "UTC-12");
        TIMEZONE_MAP.put("DDUT", "UTC+10");
        TIMEZONE_MAP.put("Samoa Standard Time", "UTC-11");
        TIMEZONE_MAP.put("ALMT", "UTC+6");
        TIMEZONE_MAP.put("Casey Time", "UTC+8");
        TIMEZONE_MAP.put("Cape Verde Time", "UTC-1");
        TIMEZONE_MAP.put("PETT", "UTC+12");
        TIMEZONE_MAP.put("NRT", "UTC+12");
        TIMEZONE_MAP.put("Srednekolymsk Time", "UTC+11");
        TIMEZONE_MAP.put("Georgia Standard Time", "UTC+4");
        TIMEZONE_MAP.put("Maldives Time", "UTC+5");
        TIMEZONE_MAP.put("Choibalsan Summer Time", "UTC+9");
        TIMEZONE_MAP.put("CAST", "UTC+8");
        TIMEZONE_MAP.put("EEST", "UTC+3");
        TIMEZONE_MAP.put("Kamchatka Time", "UTC+12");
        TIMEZONE_MAP.put("YAPT", "UTC+10");
        TIMEZONE_MAP.put("Magadan Summer Time", "UTC+12");
        TIMEZONE_MAP.put("PETST", "UTC+12");
        TIMEZONE_MAP.put("Paraguay Time", "UTC-3");
        TIMEZONE_MAP.put("OMSST", "UTC+7");
        TIMEZONE_MAP.put("Alma-Ata Time", "UTC+6");
        TIMEZONE_MAP.put("Bhutan Time", "UTC+6");
        TIMEZONE_MAP.put("PWT", "UTC+9");
        TIMEZONE_MAP.put("NST", "UTC-03:30");
        TIMEZONE_MAP.put("Uruguay Summer Time", "UTC-2");
        TIMEZONE_MAP.put("LHDT", "UTC+11");
        TIMEZONE_MAP.put("VLAST", "UTC+11");
        TIMEZONE_MAP.put("GET", "UTC+4");
        TIMEZONE_MAP.put("EAT", "UTC+3");
        TIMEZONE_MAP.put("Uzbekistan Time", "UTC+5");
        TIMEZONE_MAP.put("AZT", "UTC+4");
        TIMEZONE_MAP.put("Eastern Indonesian Time", "UTC+9");
        TIMEZONE_MAP.put("QYZT", "UTC+6");
        TIMEZONE_MAP.put("Western Greenland Time", "UTC-2");
        TIMEZONE_MAP.put("Mountain Standard Time", "UTC-7");
        TIMEZONE_MAP.put("WET", "UTC+0");
        TIMEZONE_MAP.put("Australian Western Standard Time", "UTC+8");
        TIMEZONE_MAP.put("Chatham Island Standard Time", "UTC+12:45");
        TIMEZONE_MAP.put("West Africa Summer Time", "UTC+2");
        TIMEZONE_MAP.put("Afghanistan Time", "UTC+04:30");
        TIMEZONE_MAP.put("Newfoundland Standard Time", "UTC-03:30");
        TIMEZONE_MAP.put("Tokelau Time", "UTC+13");
        TIMEZONE_MAP.put("MAWT", "UTC+5");
        TIMEZONE_MAP.put("GFT", "UTC-3");
        TIMEZONE_MAP.put("AWDT", "UTC+9");
        TIMEZONE_MAP.put("Omsk Summer Time", "UTC+7");
        TIMEZONE_MAP.put("Eastern Daylight Time", "UTC-4");
        TIMEZONE_MAP.put("IRDT", "UTC+04:30");
        TIMEZONE_MAP.put("MSD", "UTC+4");
        TIMEZONE_MAP.put("Qyzylorda Time", "UTC+6");
        TIMEZONE_MAP.put("MSK", "UTC+3");
        TIMEZONE_MAP.put("WFT", "UTC+12");
        TIMEZONE_MAP.put("PMDT", "UTC-2");
        TIMEZONE_MAP.put("SRET", "UTC+11");
        TIMEZONE_MAP.put("Arabia Daylight Time", "UTC+4");
        TIMEZONE_MAP.put("NUT", "UTC-11");
        TIMEZONE_MAP.put("MST", "UTC-7");
        TIMEZONE_MAP.put("FET", "UTC+3");
        TIMEZONE_MAP.put("ECT", "UTC-5");
        TIMEZONE_MAP.put("NZDT", "UTC+13");
        TIMEZONE_MAP.put("Whiskey Time Zone", "UTC-10");
        TIMEZONE_MAP.put("Central Standard Time", "UTC-6");
        TIMEZONE_MAP.put("Nepal Time", "UTC+05:45");
        TIMEZONE_MAP.put("VET", "UTC-4");
        TIMEZONE_MAP.put("WGT", "UTC-2");
        TIMEZONE_MAP.put("Brasília Summer Time", "UTC-2");
        TIMEZONE_MAP.put("New Zealand Standard Time", "UTC+12");
        TIMEZONE_MAP.put("EDT", "UTC-4");
        TIMEZONE_MAP.put("Quebec Time Zone", "UTC-4");
        TIMEZONE_MAP.put("Indochina Time", "UTC+7");
        TIMEZONE_MAP.put("Sakhalin Time", "UTC+11");
        TIMEZONE_MAP.put("Mauritius Time", "UTC+4");
        TIMEZONE_MAP.put("Eastern Africa Time", "UTC+3");
        TIMEZONE_MAP.put("India Standard Time", "UTC+05:30");
        TIMEZONE_MAP.put("Peru Time", "UTC-5");
        TIMEZONE_MAP.put("Gilbert Island Time", "UTC+12");
        TIMEZONE_MAP.put("NOVST", "UTC+7");
        TIMEZONE_MAP.put("Dumont-d'Urville Time", "UTC+10");
        TIMEZONE_MAP.put("AZOST", "UTC+0");
        TIMEZONE_MAP.put("AEDT", "UTC+11");
        TIMEZONE_MAP.put("Tajikistan Time", "UTC+5");
        TIMEZONE_MAP.put("MUT", "UTC+4");
        TIMEZONE_MAP.put("Golf Time Zone", "UTC+7");
        TIMEZONE_MAP.put("HKT", "UTC+8");
        TIMEZONE_MAP.put("Phoenix Island Time", "UTC+13");
        TIMEZONE_MAP.put("Vostok Time", "UTC+6");
        TIMEZONE_MAP.put("WIB", "UTC+7");
        TIMEZONE_MAP.put("Tuvalu Time", "UTC+12");
        TIMEZONE_MAP.put("EET", "UTC+2");
        TIMEZONE_MAP.put("CAT", "UTC+2");
        TIMEZONE_MAP.put("Paraguay Summer Time", "UTC-3");
        TIMEZONE_MAP.put("CHOST", "UTC+9");
        TIMEZONE_MAP.put("British Summer Time", "UTC+1");
        TIMEZONE_MAP.put("Israel Standard Time", "UTC+2");
        TIMEZONE_MAP.put("Bougainville Standard Time", "UTC+11");
        TIMEZONE_MAP.put("AZOT", "UTC-1");
        TIMEZONE_MAP.put("WARST", "UTC-3");
        TIMEZONE_MAP.put("GALT", "UTC-6");
        TIMEZONE_MAP.put("WIT", "UTC+9");
        TIMEZONE_MAP.put("Foxtrot Time Zone", "UTC+6");
        TIMEZONE_MAP.put("MVT", "UTC+5");
        TIMEZONE_MAP.put("Choibalsan Time", "UTC+8");
        TIMEZONE_MAP.put("Eastern Greenland Summer Time", "UTC+0");
        TIMEZONE_MAP.put("KRAST", "UTC+8");
        TIMEZONE_MAP.put("EAST", "UTC-6");
        TIMEZONE_MAP.put("Lord Howe Standard Time", "UTC+10:30");
        TIMEZONE_MAP.put("Guyana Time", "UTC-4");
        TIMEZONE_MAP.put("South Africa Standard Time", "UTC+2");
        TIMEZONE_MAP.put("DAVT", "UTC+7");
        TIMEZONE_MAP.put("SBT", "UTC+11");
        TIMEZONE_MAP.put("Falkland Islands Summer Time", "UTC-3");
        TIMEZONE_MAP.put("KST", "UTC+9");
        TIMEZONE_MAP.put("IOT", "UTC+6");
        TIMEZONE_MAP.put("Niue Time", "UTC-11");
        TIMEZONE_MAP.put("Hong Kong Time", "UTC+8");
        TIMEZONE_MAP.put("Kyrgyzstan Time", "UTC+6");
        TIMEZONE_MAP.put("EGT", "UTC-1");
        TIMEZONE_MAP.put("Norfolk Time", "UTC+11");
        TIMEZONE_MAP.put("CCT", "UTC+06:30");
        TIMEZONE_MAP.put("KRAT", "UTC+7");
        TIMEZONE_MAP.put("Philippine Time", "UTC+8");
        TIMEZONE_MAP.put("Cocos Islands Time", "UTC+06:30");

        TIMEZONE_FULL_NAMES = new HashMap<>();
        TIMEZONE_FULL_NAMES.put("BRT", "Brasília Time");
        TIMEZONE_FULL_NAMES.put("FJST", "Fiji Summer Time");
        TIMEZONE_FULL_NAMES.put("SCT", "Seychelles Time");
        TIMEZONE_FULL_NAMES.put("IRKST", "Irkutsk Summer Time");
        TIMEZONE_FULL_NAMES.put("CHAST", "Chatham Island Standard Time");
        TIMEZONE_FULL_NAMES.put("PYST", "Paraguay Summer Time");
        TIMEZONE_FULL_NAMES.put("FJT", "Fiji Time");
        TIMEZONE_FULL_NAMES.put("SAKT", "Sakhalin Time");
        TIMEZONE_FULL_NAMES.put("TVT", "Tuvalu Time");
        TIMEZONE_FULL_NAMES.put("AKST", "Alaska Standard Time");
        TIMEZONE_FULL_NAMES.put("MHT", "Marshall Islands Time");
        TIMEZONE_FULL_NAMES.put("NOVT", "Novosibirsk Time");
        TIMEZONE_FULL_NAMES.put("ACST", "Australian Central Standard Time");
        TIMEZONE_FULL_NAMES.put("TAHT", "Tahiti Time");
        TIMEZONE_FULL_NAMES.put("GAMT", "Gambier Time");
        TIMEZONE_FULL_NAMES.put("LINT", "Line Islands Time");
        TIMEZONE_FULL_NAMES.put("PONT", "Pohnpei Standard Time");
        TIMEZONE_FULL_NAMES.put("UYST", "Uruguay Summer Time");
        TIMEZONE_FULL_NAMES.put("TFT", "French Southern and Antarctic Time");
        TIMEZONE_FULL_NAMES.put("AKDT", "Alaska Daylight Time");
        TIMEZONE_FULL_NAMES.put("HOVT", "Hovd Time");
        TIMEZONE_FULL_NAMES.put("ACWST", "Australian Central Western Standard Time");
        TIMEZONE_FULL_NAMES.put("KUYT", "Kuybyshev Time");
        TIMEZONE_FULL_NAMES.put("MYT", "Malaysia Time");
        TIMEZONE_FULL_NAMES.put("JST", "Japan Standard Time");
        TIMEZONE_FULL_NAMES.put("ACDT", "Australian Central Daylight Time");
        TIMEZONE_FULL_NAMES.put("FKT", "Falkland Island Time");
        TIMEZONE_FULL_NAMES.put("GMT", "Greenwich Mean Time");
        TIMEZONE_FULL_NAMES.put("UYT", "Uruguay Time");
        TIMEZONE_FULL_NAMES.put("CET", "Central European Time");
        TIMEZONE_FULL_NAMES.put("EASST", "Easter Island Summer Time");
        TIMEZONE_FULL_NAMES.put("TOST", "Tonga Summer Time");
        TIMEZONE_FULL_NAMES.put("CVT", "Cape Verde Time");
        TIMEZONE_FULL_NAMES.put("A", "Alfa Time Zone");
        TIMEZONE_FULL_NAMES.put("B", "Bravo Time Zone");
        TIMEZONE_FULL_NAMES.put("ART", "Argentina Time");
        TIMEZONE_FULL_NAMES.put("BTT", "Bhutan Time");
        TIMEZONE_FULL_NAMES.put("C", "Charlie Time Zone");
        TIMEZONE_FULL_NAMES.put("AZST", "Azerbaijan Summer Time");
        TIMEZONE_FULL_NAMES.put("D", "Delta Time Zone");
        TIMEZONE_FULL_NAMES.put("E", "Echo Time Zone");
        TIMEZONE_FULL_NAMES.put("F", "Foxtrot Time Zone");
        TIMEZONE_FULL_NAMES.put("G", "Golf Time Zone");
        TIMEZONE_FULL_NAMES.put("H", "Hotel Time Zone");
        TIMEZONE_FULL_NAMES.put("I", "India Time Zone");
        TIMEZONE_FULL_NAMES.put("K", "Kilo Time Zone");
        TIMEZONE_FULL_NAMES.put("L", "Lima Time Zone");
        TIMEZONE_FULL_NAMES.put("M", "Mike Time Zone");
        TIMEZONE_FULL_NAMES.put("N", "November Time Zone");
        TIMEZONE_FULL_NAMES.put("UZT", "Uzbekistan Time");
        TIMEZONE_FULL_NAMES.put("O", "Oscar Time Zone");
        TIMEZONE_FULL_NAMES.put("P", "Papa Time Zone");
        TIMEZONE_FULL_NAMES.put("Q", "Quebec Time Zone");
        TIMEZONE_FULL_NAMES.put("R", "Romeo Time Zone");
        TIMEZONE_FULL_NAMES.put("S", "Sierra Time Zone");
        TIMEZONE_FULL_NAMES.put("SAMT", "Samara Time");
        TIMEZONE_FULL_NAMES.put("T", "Tango Time Zone");
        TIMEZONE_FULL_NAMES.put("U", "Uniform Time Zone");
        TIMEZONE_FULL_NAMES.put("V", "Victor Time Zone");
        TIMEZONE_FULL_NAMES.put("W", "Whiskey Time Zone");
        TIMEZONE_FULL_NAMES.put("X", "X-ray Time Zone");
        TIMEZONE_FULL_NAMES.put("YAKT", "Yakutsk Time");
        TIMEZONE_FULL_NAMES.put("Y", "Yankee Time Zone");
        TIMEZONE_FULL_NAMES.put("Z", "Zulu Time Zone");
        TIMEZONE_FULL_NAMES.put("CEST", "Central European Summer Time");
        TIMEZONE_FULL_NAMES.put("YEKST", "Yekaterinburg Summer Time");
        TIMEZONE_FULL_NAMES.put("NFDT", "Norfolk Daylight Time");
        TIMEZONE_FULL_NAMES.put("IRKT", "Irkutsk Time");
        TIMEZONE_FULL_NAMES.put("ACT", "Acre Time");
        TIMEZONE_FULL_NAMES.put("KGT", "Kyrgyzstan Time");
        TIMEZONE_FULL_NAMES.put("ICT", "Indochina Time");
        TIMEZONE_FULL_NAMES.put("CXT", "Christmas Island Time");
        TIMEZONE_FULL_NAMES.put("RET", "Reunion Time");
        TIMEZONE_FULL_NAMES.put("SGT", "Singapore Time");
        TIMEZONE_FULL_NAMES.put("WAST", "West Africa Summer Time");
        TIMEZONE_FULL_NAMES.put("FNT", "Fernando de Noronha Time");
        TIMEZONE_FULL_NAMES.put("MAGST", "Magadan Summer Time");
        TIMEZONE_FULL_NAMES.put("CLST", "Chile Summer Time");
        TIMEZONE_FULL_NAMES.put("WITA", "Central Indonesian Time");
        TIMEZONE_FULL_NAMES.put("IDT", "Israel Daylight Time");
        TIMEZONE_FULL_NAMES.put("OMST", "Omsk Standard Time");
        TIMEZONE_FULL_NAMES.put("TJT", "Tajikistan Time");
        TIMEZONE_FULL_NAMES.put("EGST", "Eastern Greenland Summer Time");
        TIMEZONE_FULL_NAMES.put("HST", "Hawaii Standard Time");
        TIMEZONE_FULL_NAMES.put("ANAST", "Anadyr Summer Time");
        TIMEZONE_FULL_NAMES.put("CIDST", "Cayman Islands Daylight Saving Time");
        TIMEZONE_FULL_NAMES.put("AQTT", "Aqtobe Time");
        TIMEZONE_FULL_NAMES.put("BRST", "Brasília Summer Time");
        TIMEZONE_FULL_NAMES.put("MMT", "Myanmar Time");
        TIMEZONE_FULL_NAMES.put("ULAST", "Ulaanbaatar Summer Time");
        TIMEZONE_FULL_NAMES.put("TKT", "Tokelau Time");
        TIMEZONE_FULL_NAMES.put("HOVST", "Hovd Summer Time");
        TIMEZONE_FULL_NAMES.put("WAT", "West Africa Time");
        TIMEZONE_FULL_NAMES.put("AFT", "Afghanistan Time");
        TIMEZONE_FULL_NAMES.put("NPT", "Nepal Time");
        TIMEZONE_FULL_NAMES.put("HDT", "Hawaii-Aleutian Daylight Time");
        TIMEZONE_FULL_NAMES.put("TLT", "East Timor Time");
        TIMEZONE_FULL_NAMES.put("WT", "Western Sahara Standard Time");
        TIMEZONE_FULL_NAMES.put("YAKST", "Yakutsk Summer Time");
        TIMEZONE_FULL_NAMES.put("PDT", "Pacific Daylight Time");
        TIMEZONE_FULL_NAMES.put("KOST", "Kosrae Time");
        TIMEZONE_FULL_NAMES.put("SYOT", "Syowa Time");
        TIMEZONE_FULL_NAMES.put("CKT", "Cook Island Time");
        TIMEZONE_FULL_NAMES.put("VOST", "Vostok Time");
        TIMEZONE_FULL_NAMES.put("MART", "Marquesas Time");
        TIMEZONE_FULL_NAMES.put("TMT", "Turkmenistan Time");
        TIMEZONE_FULL_NAMES.put("LHST", "Lord Howe Standard Time");
        TIMEZONE_FULL_NAMES.put("PET", "Peru Time");
        TIMEZONE_FULL_NAMES.put("DDUT", "Dumont-d'Urville Time");
        TIMEZONE_FULL_NAMES.put("AWST", "Australian Western Standard Time");
        TIMEZONE_FULL_NAMES.put("NZST", "New Zealand Standard Time");
        TIMEZONE_FULL_NAMES.put("SAST", "South Africa Standard Time");
        TIMEZONE_FULL_NAMES.put("CLT", "Chile Standard Time");
        TIMEZONE_FULL_NAMES.put("ALMT", "Alma-Ata Time");
        TIMEZONE_FULL_NAMES.put("PETT", "Kamchatka Time");
        TIMEZONE_FULL_NAMES.put("NRT", "Nauru Time");
        TIMEZONE_FULL_NAMES.put("CHOT", "Choibalsan Time");
        TIMEZONE_FULL_NAMES.put("WGST", "Western Greenland Summer Time");
        TIMEZONE_FULL_NAMES.put("CAST", "Casey Time");
        TIMEZONE_FULL_NAMES.put("EEST", "Eastern European Summer Time");
        TIMEZONE_FULL_NAMES.put("YAPT", "Yap Time");
        TIMEZONE_FULL_NAMES.put("PETST", "Kamchatka Summer Time");
        TIMEZONE_FULL_NAMES.put("OMSST", "Omsk Summer Time");
        TIMEZONE_FULL_NAMES.put("PWT", "Palau Time");
        TIMEZONE_FULL_NAMES.put("ULAT", "Ulaanbaatar Time");
        TIMEZONE_FULL_NAMES.put("NST", "Newfoundland Standard Time");
        TIMEZONE_FULL_NAMES.put("LHDT", "Lord Howe Daylight Time");
        TIMEZONE_FULL_NAMES.put("VLAST", "Vladivostok Summer Time");
        TIMEZONE_FULL_NAMES.put("GET", "Georgia Standard Time");
        TIMEZONE_FULL_NAMES.put("TOT", "Tonga Time");
        TIMEZONE_FULL_NAMES.put("EAT", "Eastern Africa Time");
        TIMEZONE_FULL_NAMES.put("AZT", "Azerbaijan Time");
        TIMEZONE_FULL_NAMES.put("PMST", "Pierre & Miquelon Standard Time");
        TIMEZONE_FULL_NAMES.put("PGT", "Papua New Guinea Time");
        TIMEZONE_FULL_NAMES.put("ANAT", "Anadyr Time");
        TIMEZONE_FULL_NAMES.put("NCT", "New Caledonia Time");
        TIMEZONE_FULL_NAMES.put("VLAT", "Vladivostok Time");
        TIMEZONE_FULL_NAMES.put("QYZT", "Qyzylorda Time");
        TIMEZONE_FULL_NAMES.put("WET", "Western European Time");
        TIMEZONE_FULL_NAMES.put("MAWT", "Mawson Time");
        TIMEZONE_FULL_NAMES.put("GFT", "French Guiana Time");
        TIMEZONE_FULL_NAMES.put("AWDT", "Australian Western Daylight Time");
        TIMEZONE_FULL_NAMES.put("CIST", "Cayman Islands Standard Time");
        TIMEZONE_FULL_NAMES.put("IRDT", "Iran Daylight Time");
        TIMEZONE_FULL_NAMES.put("YEKT", "Yekaterinburg Time");
        TIMEZONE_FULL_NAMES.put("PHT", "Philippine Time");
        TIMEZONE_FULL_NAMES.put("MSD", "Moscow Daylight Time");
        TIMEZONE_FULL_NAMES.put("NDT", "Newfoundland Daylight Time");
        TIMEZONE_FULL_NAMES.put("MSK", "Moscow Standard Time");
        TIMEZONE_FULL_NAMES.put("WFT", "Wallis and Futuna Time");
        TIMEZONE_FULL_NAMES.put("EST", "Eastern Standard Time");
        TIMEZONE_FULL_NAMES.put("IRST", "Iran Standard Time");
        TIMEZONE_FULL_NAMES.put("PMDT", "Pierre & Miquelon Daylight Time");
        TIMEZONE_FULL_NAMES.put("SRET", "Srednekolymsk Time");
        TIMEZONE_FULL_NAMES.put("COT", "Colombia Time");
        TIMEZONE_FULL_NAMES.put("NUT", "Niue Time");
        TIMEZONE_FULL_NAMES.put("MST", "Mountain Standard Time");
        TIMEZONE_FULL_NAMES.put("ORAT", "Oral Time");
        TIMEZONE_FULL_NAMES.put("FET", "Further-Eastern European Time");
        TIMEZONE_FULL_NAMES.put("VUT", "Vanuatu Time");
        TIMEZONE_FULL_NAMES.put("ECT", "Ecuador Time");
        TIMEZONE_FULL_NAMES.put("NZDT", "New Zealand Daylight Time");
        TIMEZONE_FULL_NAMES.put("VET", "Venezuelan Standard Time");
        TIMEZONE_FULL_NAMES.put("UTC", "Coordinated Universal Time");
        TIMEZONE_FULL_NAMES.put("WGT", "Western Greenland Time");
        TIMEZONE_FULL_NAMES.put("ChST", "Chamorro Standard Time");
        TIMEZONE_FULL_NAMES.put("WEST", "Western European Summer Time");
        TIMEZONE_FULL_NAMES.put("BNT", "Brunei Darussalam Time");
        TIMEZONE_FULL_NAMES.put("EDT", "Eastern Daylight Time");
        TIMEZONE_FULL_NAMES.put("TRT", "Turkey Time");
        TIMEZONE_FULL_NAMES.put("AEST", "Australian Eastern Standard Time");
        TIMEZONE_FULL_NAMES.put("WAKT", "Wake Time");
        TIMEZONE_FULL_NAMES.put("MDT", "Mountain Daylight Time");
        TIMEZONE_FULL_NAMES.put("NFT", "Norfolk Time");
        TIMEZONE_FULL_NAMES.put("MAGT", "Magadan Time");
        TIMEZONE_FULL_NAMES.put("GYT", "Guyana Time");
        TIMEZONE_FULL_NAMES.put("BOT", "Bolivia Time");
        TIMEZONE_FULL_NAMES.put("NOVST", "Novosibirsk Summer Time");
        TIMEZONE_FULL_NAMES.put("AZOST", "Azores Summer Time");
        TIMEZONE_FULL_NAMES.put("AEDT", "Australian Eastern Daylight Time");
        TIMEZONE_FULL_NAMES.put("MUT", "Mauritius Time");
        TIMEZONE_FULL_NAMES.put("HKT", "Hong Kong Time");
        TIMEZONE_FULL_NAMES.put("WIB", "Western Indonesian Time");
        TIMEZONE_FULL_NAMES.put("EET", "Eastern European Time");
        TIMEZONE_FULL_NAMES.put("AoE", "Anywhere on Earth");
        TIMEZONE_FULL_NAMES.put("CAT", "Central Africa Time");
        TIMEZONE_FULL_NAMES.put("PKT", "Pakistan Standard Time");
        TIMEZONE_FULL_NAMES.put("CHOST", "Choibalsan Summer Time");
        TIMEZONE_FULL_NAMES.put("AZOT", "Azores Time");
        TIMEZONE_FULL_NAMES.put("WARST", "Western Argentine Summer Time");
        TIMEZONE_FULL_NAMES.put("GALT", "Galapagos Time");
        TIMEZONE_FULL_NAMES.put("WIT", "Eastern Indonesian Time");
        TIMEZONE_FULL_NAMES.put("FKST", "Falkland Islands Summer Time");
        TIMEZONE_FULL_NAMES.put("MVT", "Maldives Time");
        TIMEZONE_FULL_NAMES.put("GILT", "Gilbert Island Time");
        TIMEZONE_FULL_NAMES.put("SRT", "Suriname Time");
        TIMEZONE_FULL_NAMES.put("CHUT", "Chuuk Time");
        TIMEZONE_FULL_NAMES.put("KRAST", "Krasnoyarsk Summer Time");
        TIMEZONE_FULL_NAMES.put("CHADT", "Chatham Island Daylight Time");
        TIMEZONE_FULL_NAMES.put("EAST", "Easter Island Standard Time");
        TIMEZONE_FULL_NAMES.put("DAVT", "Davis Time");
        TIMEZONE_FULL_NAMES.put("SBT", "Solomon Islands Time");
        TIMEZONE_FULL_NAMES.put("KST", "Korea Standard Time");
        TIMEZONE_FULL_NAMES.put("IOT", "Indian Chagos Time");
        TIMEZONE_FULL_NAMES.put("EGT", "East Greenland Time");
        TIMEZONE_FULL_NAMES.put("CCT", "Cocos Islands Time");
        TIMEZONE_FULL_NAMES.put("SST", "Samoa Standard Time");
        TIMEZONE_FULL_NAMES.put("PHOT", "Phoenix Island Time");
        TIMEZONE_FULL_NAMES.put("KRAT", "Krasnoyarsk Time");

        TIMEZONE_CONFLICTS = new HashMap<>();
        TIMEZONE_CONFLICTS.put("ADT", Arrays.asList("Atlantic Daylight Time", "Arabia Daylight Time"));
        TIMEZONE_CONFLICTS.put("CDT", Arrays.asList("Central Daylight Time", "Cuba Daylight Time"));
        TIMEZONE_CONFLICTS.put("BST", Arrays.asList("British Summer Time", "Bangladesh Standard Time", "Bougainville Standard Time"));
        TIMEZONE_CONFLICTS.put("AST", Arrays.asList("Atlantic Standard Time", "Arabia Standard Time"));
        TIMEZONE_CONFLICTS.put("AMST", Arrays.asList("Amazon Summer Time", "Armenia Summer Time"));
        TIMEZONE_CONFLICTS.put("CST", Arrays.asList("Central Standard Time", "China Standard Time", "Cuba Standard Time"));
        TIMEZONE_CONFLICTS.put("AMT", Arrays.asList("Amazon Time", "Armenia Time"));
        TIMEZONE_CONFLICTS.put("GST", Arrays.asList("Gulf Standard Time", "South Georgia Time"));
        TIMEZONE_CONFLICTS.put("WST", Arrays.asList("West Samoa Time", "Western Sahara Summer Time"));
        TIMEZONE_CONFLICTS.put("PYT", Arrays.asList("Paraguay Time", "Pyongyang Time"));
        TIMEZONE_CONFLICTS.put("IST", Arrays.asList("India Standard Time", "Irish Standard Time", "Israel Standard Time"));
    }

    static void main(String[] args) throws IOException {
        Map<String, String> timezoneMap = new HashMap<>();
        Map<String, String> timezoneFullNames = new HashMap<>();
        Map<String, List<String>> timezoneConflicts = new HashMap<>();

        for (Element elt : Jsoup.parse(new File("/tmp/timeanddate.html")).select(".tad-table tbody tr")) {
            String name = elt.select("td:first-child").text().trim();
            String fullName = elt.select("td:nth-child(2) .tad-cell__wrap > div").first().ownText().trim();
            String offset = elt.select("td:last-child").text().trim().replace(" ", "");

            // UTC+8:45 => UTC+08:45
            if (offset.matches("UTC[+-][0-9]:[0-9]{2}")) {
                offset = offset.replace("+", "+0").replace("-", "-0");
            }

            try {
                ZoneId.of(offset);
            } catch (DateTimeException e) {
                // the timezone ended up invalid: skip it.
                logger.info("Time zone offset {} is invalid", offset);
                continue;
            }

            timezoneMap.put(fullName, offset);
            if (!timezoneConflicts.containsKey(name)) {
                // there is no conflict (yet): add to the valid timezone map.
                timezoneMap.put(name, offset);
                timezoneFullNames.put(name, fullName);
                timezoneConflicts.put(name, new ArrayList<>(Collections.singletonList(fullName)));
            } else {
                timezoneConflicts.get(name).add(fullName);
                timezoneFullNames.remove(name);

                if (timezoneMap.containsKey(name) && !timezoneMap.get(name).equals(offset)) {
                    // there is a conflict and the offsets are different! remove it.
                    timezoneMap.remove(name);
                }
            }
        }

        // filter out conflicts that aren't conflicts.
        Map<String, List<String>> actualConflicts = new HashMap<>();
        for (Map.Entry<String, List<String>> conflict : timezoneConflicts.entrySet()) {
            if (!timezoneMap.containsKey(conflict.getKey())) {
                actualConflicts.put(conflict.getKey(), conflict.getValue());
            }
        }
        timezoneConflicts = actualConflicts;

        System.out.println("\t\tTIMEZONE_MAP = new HashMap<>();");
        for (Map.Entry<String, String> entry : timezoneMap.entrySet()) {
            System.out.println("\t\tTIMEZONE_MAP.put(\"" + entry.getKey() + "\", \"" + entry.getValue() + "\");");
        }
        System.out.println();

        System.out.println("\t\tTIMEZONE_FULL_NAMES = new HashMap<>();");
        for (Map.Entry<String, String> entry : timezoneFullNames.entrySet()) {
            System.out.println("\t\tTIMEZONE_FULL_NAMES.put(\"" + entry.getKey() + "\", \"" + entry.getValue() + "\");");
        }
        System.out.println();

        System.out.println("\t\tTIMEZONE_CONFLICTS = new HashMap<>();");
        for (Map.Entry<String, List<String>> entry : timezoneConflicts.entrySet()) {
            System.out.println("\t\tTIMEZONE_CONFLICTS.put(\"" + entry.getKey() + "\", Arrays.asList(\"" + String.join("\", \"", entry.getValue()) + "\"));");
        }
    }
}
