services:
  hourly-crontabs:
    image: max480/random-stuff-backend
    command: ["/bin/bash", "-c", "sed -i 's/CrontabRunner/CrontabRunner --hourly/' /app/run_bot.sh && sed -i 's/-Xmx256m/-Xmx128m/' /app/run_bot.sh && /app/run_bot.sh"]
    env_file: secret_constants_backend
    volumes:
      - /home/debian/backend:/backend
      - /home/debian/shared:/shared
      - /home/debian/logs:/logs
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 384M
